disabled_rules:
  - trailing_whitespace
  - identifier_name
  - type_name
  - nesting

line_length:
  warning: 160
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false